[40기 - 원승현] Assignment 1: Layered Pattern
wecode-bootcamp-korea/40-backend-westagram-3 pull request #1
Opened 2022-11-23 06:56 UTC by tmdgus4118

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-23 09:25 UTC, SeongJoon-K requested changes
승현님 ! 첫 과제인데 너무 잘 해주셨습니다 ! 
수정 사항 반영해서 다시 push 라벨 변경해주시면 감사하겠습니다 !

2022-11-23 09:25 UTC, SeongJoon-K commented on WonSeungHyun/.env.sample
> +TYPEORM_LOGGING =TRUE
안녕하세요 승현님 !! 세팅을 너무 잘 해주셨네요 ! 동일하게 HOST, PORT도 수정해 주시면 감사하겠습니다!
```suggestion
PORT = YOUR PORT NUMBER SHOULD BE HERE!

TYPEORM_CONNECTION = RDBMS_TYPE
TYPEORM_HOST = YOUR HOST
TYPEORM_USERNAME = USERNAME
TYPEORM_PASSWORD = myPassword
TYPEORM_DATABASE = myDB
TYPEORM_PORT = YOUR PORT
TYPEORM_LOGGING =TRUE
```

2022-11-23 09:25 UTC, SeongJoon-K commented on WonSeungHyun/app.js
> +dotenv.config();
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
    - Bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지

```suggestion
//// Built-in package
const http = require('http')

//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();
```

2022-11-23 09:25 UTC, SeongJoon-K commented on WonSeungHyun/app.js
> +});
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- 추가로 `DataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
아래는 예시입니다.
```suggestion
const appDataSource = new DataSource({
  type: process.env.TYPEORM_CONNECTION,
  host: process.env.TYPEORM_HOST,
  port: process.env.TYPEORM_PORT,
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
});

appDataSource.initialize().then(() => {
  console.log("Data Source has been initialized!");
});
```

2022-11-24 08:20 UTC, sangwoong03 requested changes

2022-11-24 08:20 UTC, sangwoong03 commented on WonSeungHyun/app.js
> +>>>>>>> Stashed changes
불필요한 코드가 포함된 것 같네요~!
해당 코드 수정해서 다시 push 해주세요!

2022-11-24 08:20 UTC, sangwoong03 commented on WonSeungHyun/app.js
> +const { DataSource, InsertValuesMissingError } = require("typeorm");
`InsertValueMissingError`는 사용하지 않는 모듈인 것 같네요~! 삭제 후 다시 push 해주세요!

2022-11-25 03:05 UTC, SeongJoon-K approved these changes

2022-11-25 03:05 UTC, merged