Feature/hyungjin jeon crud table
wecode-bootcamp-korea/40-backend-westagram-3 pull request #11
Opened 2022-11-24 11:15 UTC by hjcod

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-게시물 등록 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 제목과 내용 필수
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항

![Assignmnet3](https://user-images.githubusercontent.com/106718631/203771016-55af6c58-92da-430d-895c-25cc7ffa9af3.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-25 06:17 UTC, SeongJoon-K requested changes
형진님 ! file changed 에 형진님 디렉토리가 아닌, 다른 분들의 디렉토리와 최상위 디렉토리의 gitignore에도 수정사항이 존재합니다. 이렇게 되었을 때, 다른분의 Pull request가 merge 될시 conflict가 발생할 수 있습니다. 해당 수정사항을 다시 확인하시고 push 해 주세요!

2022-11-25 06:20 UTC, SeongJoon-K requested changes

2022-11-25 06:20 UTC, SeongJoon-K commented on hyungjin/app.js
> +dotenv.config()
```suggestion
const http =require ("http");

const express = require("express");
const cors = require("cors");
const morgan =  require("morgan");
const dotenv = require("dotenv");

const { DataSource } = require('typeorm'); 

dotenv.config()
```

2022-11-25 06:20 UTC, SeongJoon-K commented on hyungjin/app.js
> +  });
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- 추가로 `DataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2022-11-25 06:20 UTC, SeongJoon-K commented on hyungjin/db/migrations/20221124075625_create_signup.sql
> +)
```suggestion
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)
```

2022-11-25 06:20 UTC, SeongJoon-K commented on hyungjin/db/migrations/20221124083118_create_posts_table.sql
> +
```suggestion
-- migrate:up

CREATE TABLE posts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)

```

2022-11-25 06:20 UTC, SeongJoon-K commented on hyungjin/package.json
> +    "typeorm": "^0.3.10"
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.

2022-11-30 01:47 UTC, sangwoong03 requested changes

2022-11-30 01:47 UTC, sangwoong03 commented on hyunjinjeon/db/migrations/20221128042517_create_signup_table.sql
> +);
회원가입 시 이메일 혹은 아이디를 중복하는 프로세스를 경험해보신 적이 있을 것입니다.

인스타그램을 모티브로 구현하고 있는 WESTAGRAM에서도 특정 정보가 중복이 되어서는 안되기 때문에 email 컬럼에 unique 속성을 추가해주세요!

제약조건의 이름을 설정한다면, 추후 비활성화, 삭제 등 관리에 용이할 수 있어 아래의 쿼리문을 참고하여 수정해주세요!

`CONSTRAINT users_email_ukey UNIQUE (email);`

2022-11-30 01:47 UTC, sangwoong03 commented on .gitignore
> +my_settings.py
python 파일을 여기서 사용하지 않으니 삭제해도 좋습니다!

2022-11-30 01:47 UTC, sangwoong03 commented on hyunjinjeon/app.js
> + app.get('/lookposts',async(req,res)=>{
HTTP GET 메서드 자체의 의미를 보았을 때 특정 리소스를 조회하거나 찾는다는 의미가 있습니다.

따라서 RESTful API를 구현하는데 있어 엔드포인트에 동사형이 아닌 명사형으로 작성하도록 권장하고 있습니다.

```suggestion
 app.get('/posts', async(req, res)=>{
```

2022-11-30 01:47 UTC, sangwoong03 commented on hyunjinjeon/app.js
> +})
게시글만 받아오면 되는 api로 보이기 때문에 엔드포인트는 `/posts~` 로 시작할 수 있게 수정해주세요! 

posts 테이블에서 user_id 값을 통해 특정 게시글만 가져오면 되므로 JOIN 키워드를 활용하여 쿼리문을 하나로 줄여주세요!

2022-11-30 01:47 UTC, sangwoong03 commented on hyunjinjeon/app.js
> +    const {userid,postid} = req.body;
request의 body로 데이터를 받아오는 방식을 선택해주세요!

path paramater로 특정 데이터를 요청하는 경우에는 해당 정보 상세 정보를 조회하거나, 단순 삭제하는 경우에 사용됩니다!

2022-11-30 06:40 UTC, SeongJoon-K requested changes

2022-11-30 06:40 UTC, SeongJoon-K commented on db/migrations/20221128042517_create_signup_table.sql
> +
형진님 ! 의미 없는 줄 바꿈은 지양해 주세요! 아래와 같이 수정해 주시면 감사하겠습니다 !
```suggestion
-- migrate:up   
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  email varchar(200) NOT NULL,
  profile_image varchar(1000) DEFAULT NULL,
  password varchar(200) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- migrate:down
DROP TABLE users;
```

2022-11-30 06:40 UTC, SeongJoon-K commented on db/migrations/20221128042659_create_post_table.sql
> +
```suggestion
-- migrate:up
CREATE TABLE posts (
  id int NOT NULL AUTO_INCREMENT,
  title varchar(50) NOT NULL,
  content varchar(2000) DEFAULT NULL,
  post_image varchar(1000) DEFAULT NULL,
  user_id int NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id),
 FOREIGN KEY (user_id) REFERENCES users (id)
);

-- migrate:down
DROP TABLE posts;
```

2022-11-30 06:40 UTC, SeongJoon-K commented on hyunjinjeon/app.js
> +      })
형진님 ! 특정 유저를 조회하는 엔드포인트를 정할 때, 
`/userpost/:userId` 를 본다면 어떠한 기능을 하는 엔드포인트인지 제대로 전달이 되지 않을 수 있습니다.
`/posts/:userId`는 어떤가요? 조금 더 `Restful` 하지 않나요?
여기서 말씀드린 RestFul 하다는 것이 현 시점에서 조금 어렵게 다가올 수 있지만, 한 번 찾아보시는 건 어떨까요?
https://velog.io/@somday/RESTful-API-%EC%9D%B4%EB%9E%80

2022-11-30 06:40 UTC, SeongJoon-K commented on hyunjinjeon/app.js
> +  })
형진님! 저희가 보내는 patch, 혹은 delete에 어떤 작업을 의미하는지 이미 내포되어 있기 때문에 
엔드포인트에 수정한다 라는 것을 명시해주지 않아도 됩니다. 오히려 의미의 중복이 발생할 수 있기 때문에
해당 부분은 지양해야 합니다 !
```suggestion
app.patch("/posts/:postId", async (req, res) => {
  const postId = req.params.postId;
  const {content} = req.body;
  await appDataSource.query(
    `UPDATE posts SET
      content = ?
    WHERE id = ${postId}
    `,[content]);
  const post = await appDataSource.query(
    `SELECT
      users.id as userId,
      users.name as userName,
      posts.id as postingId,
      posts.title as postingTitle,
      posts.content as postingContent
    FROM posts INNER JOIN users on users.id = posts.user_id where posts.id like ${postId};`,
    );
    const result = post[0];
    res.status(204).json({data : result});
  })
```

2022-11-30 06:40 UTC, SeongJoon-K commented on hyunjinjeon/app.js
> +
위 피드백과 같이 restful의 의미를 파악하시고, 다시 수정해 주세요!

2022-12-01 01:26 UTC, SeongJoon-K requested changes

2022-12-01 01:26 UTC, SeongJoon-K commented on hyunjinjeon/app.js
> +      })
```suggestion
app.get("/post/:userId", async (req,res) => {
  const userId = req.params.userId;
    await appDataSource.query(
      `SELECT 
        users.id as userId,
        users.profile_image as userporfileImage,
        JSON_ARRAYAGG( 
        JSON_OBJECT(    
          'postingId',posts.id,
          'postingTitle',posts.title,
          'postingContent',posts.content)) as posting
      FROM users
      LEFT JOIN posts ON users.id = posts.user_id 
      WHERE users.id=${userId}
      GROUP BY users.id;
      `,(err, row)=>
      {res.status(200).json({data:row});});
})
```

2022-12-01 01:26 UTC, SeongJoon-K commented on hyunjinjeon/app.js
> +})
```suggestion
//좋아요 누르기 엔드포인트
app.post('/likes',async(req,res)=>{
    const {userId,postId} = req.body
    await appDataSource.query(
      `INSERT INTO likes (
        user_id,
        post_id
     ) VALUES(?, ?);
    `,
    [userId, postId]);
    res.status(201).json({message: "likeCreated"})
})
```

2022-12-05 01:10 UTC, SeongJoon-K approved these changes

2022-12-05 01:10 UTC, merged